Repository rakutentech/engineering-blog, pull requests merged in 2021-07, with the labels that each got.

#3 Fix bogus alignment in article meta info
  assets/scss/main.sass
Labels: bug

#1 elm @ Rakuten post
  content/post/elm-in-rakuten/images/debugger.gif
  content/post/elm-in-rakuten/images/dynamic-vs-static.png
  content/post/elm-in-rakuten/images/escape.jpg
  content/post/elm-in-rakuten/images/john-carmack-on-errors.png
  content/post/elm-in-rakuten/images/penrose-triangle.jpg
  content/post/elm-in-rakuten/images/the-elm-architecture-animation.gif
  content/post/elm-in-rakuten/images/the-elm-architecture.jpg
  content/post/elm-in-rakuten/images/the-elm-architecture.svg
  content/post/elm-in-rakuten/index.md
  static/images/elm-in-rakuten.png
Labels: blog post

#4 feature: add cc-by license
  archetypes/default.md
  assets/scss/main.sass
  layouts/partials/footer.html
  static/fonts/cc-fontello.woff2
Labels: enhancement

#5 bug: footer columns were vertically-centered
  assets/scss/main.sass
Labels: bug

#9 bug: .nojekyll was missing
  static/.nojekyll
Labels: bug

#8 bug: the generated assests were not being minified
  deploy
Labels: bug

#6 chore: update theme
  config.yaml
  go.mod
  go.sum
Labels: enhancement

#14 remove unused .forestry/
  .forestry/front_matter/templates/author.yml
  .forestry/front_matter/templates/home-hero.yml
  .forestry/front_matter/templates/home.yml
  .forestry/front_matter/templates/post.yml
  .forestry/settings.yml
Labels: enhancement

#18 add CNAME to `static/`
  static/CNAME
Labels: enhancement
